# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: "ksergey блог"
description:
url: "http://ksergey.github.io"
baseurl: "/"

author:
    name: "Sergey Kovalevich"

paginate: 16

gems:
    - "jekyll-paginate"
