# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ksergey's pirate bay
email: inndie@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    The volcano erupted, but they dug a trench
    And diverted the lava into the sea
    Where it found a spectacular pier
    They were attacked by the pirates but defeated them
    With bamboo bazookas firing
    Sea-urchins packed with home-made nitro-glycerin.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://ksergey.github.io" # the base hostname & protocol for your site
twitter_username: ksergey_
github_username:  ksergey

# Build settings
markdown: kramdown
