# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: random gaming experience
tagline:
description: play hard, don't die
url: http://ksergey.github.io
baseurl: /

author:
    name: Sergey Kovalevich
    url: https://twitter.com/ksergey_

paginate: 16

gems:
    - jekyll-paginate
    - jekyll-youtube
