# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: "ksergey"
description: "Дело было вечером, Делать было нечего"
url: "http://ksergey.github.io"
baseurl: "/"

author:
    name: "Sergey Kovalevich"

gems: [ "jekyll-paginate", "jekyll-gist" ]

paginate: 8
