# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title: ksergey's pirate bay
tagline: Yo-ho-ho!
description: no description here
url: http://ksergey.github.io
baseurl: /

author:
    name: Sergey Kovalevich
    url: https://twitter.com/ksergey_

paginate: 10

# Custom vars
version: 0.0.1
