# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: "блог ksergey"
description:
url: "http://ksergey.github.io"
baseurl: "/"

author:
    name: "Sergey Kovalevich"

gems:
    - "jekyll-paginate"

paginate: 8
