# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: "ksergey's experience"
tagline:
description: "play hard, don't die"
url: "http://ksergey.github.io"
baseurl: "/blog"

author:
    name: "Sergey Kovalevich"

paginate: 16

gems:
    - "jekyll-paginate"
